### ISSUE TITLE
My git-annex build does not work

### ISSUE THREAD

**Issue by seanparsons** [NixOS/cabal2nix#381] opened 2018-10-30 21:23 UTC
I've been experimenting with git-annex and oddly the build is failing because git isn't available to it, which seems really odd and doesn't tie up with builds I've found on Hydra: https://hydra.nixos.org/build/73904383/nixlog/1

Long pile of output from the build follows:
```
sean@lenovo ~/w/git-annex (master)> nix-build .
these derivations will be built:
  /nix/store/q1r40skrfc5dj3wwj4048y4z3ijigl0y-git-annex-6.20181011.drv
building '/nix/store/q1r40skrfc5dj3wwj4048y4z3ijigl0y-git-annex-6.20181011.drv'...
setupCompilerEnvironmentPhase
Build with /nix/store/w8ckird699qc09np3bc3h47r5g86ab8s-ghc-8.2.2.
ignoring (possibly broken) abi-depends field for packages
unpacking sources
unpacking source archive /nix/store/7mjg3mg7r7wa9rvl7pz8zc14imi6zjqs-git-annex
source root is git-annex
patching sources
compileBuildDriverPhase
setupCompileFlags: -package-db=/tmp/nix-build-git-annex-6.20181011.drv-0/package.conf.d -j1 -threaded
[ 1 of 33] Compiling Utility.Applicative ( Utility/Applicative.hs, /tmp/nix-build-git-annex-6.20181011.drv-0/Utility/Applicative.o )
[ 2 of 33] Compiling Utility.Data     ( Utility/Data.hs, /tmp/nix-build-git-annex-6.20181011.drv-0/Utility/Data.o )
[ 3 of 33] Compiling Utility.Exception ( Utility/Exception.hs, /tmp/nix-build-git-annex-6.20181011.drv-0/Utility/Exception.o )
[ 4 of 33] Compiling Utility.Env.Basic ( Utility/Env/Basic.hs, /tmp/nix-build-git-annex-6.20181011.drv-0/Utility/Env/Basic.o )
[ 5 of 33] Compiling Build.Mans       ( Build/Mans.hs, /tmp/nix-build-git-annex-6.20181011.drv-0/Build/Mans.o )
[ 6 of 33] Compiling Utility.FileSize ( Utility/FileSize.hs, /tmp/nix-build-git-annex-6.20181011.drv-0/Utility/FileSize.o )
[ 7 of 33] Compiling Utility.Misc     ( Utility/Misc.hs, /tmp/nix-build-git-annex-6.20181011.drv-0/Utility/Misc.o )
[ 8 of 33] Compiling Utility.Monad    ( Utility/Monad.hs, /tmp/nix-build-git-annex-6.20181011.drv-0/Utility/Monad.o )
[ 9 of 33] Compiling Build.Version    ( Build/Version.hs, /tmp/nix-build-git-annex-6.20181011.drv-0/Build/Version.o )
[10 of 33] Compiling Utility.PartialPrelude ( Utility/PartialPrelude.hs, /tmp/nix-build-git-annex-6.20181011.drv-0/Utility/PartialPrelude.o )
[11 of 33] Compiling Utility.Process.Shim ( Utility/Process/Shim.hs, /tmp/nix-build-git-annex-6.20181011.drv-0/Utility/Process/Shim.o )
[12 of 33] Compiling Utility.Process  ( Utility/Process.hs, /tmp/nix-build-git-annex-6.20181011.drv-0/Utility/Process.o )
[13 of 33] Compiling Utility.Network  ( Utility/Network.hs, /tmp/nix-build-git-annex-6.20181011.drv-0/Utility/Network.o )
[14 of 33] Compiling Utility.Split    ( Utility/Split.hs, /tmp/nix-build-git-annex-6.20181011.drv-0/Utility/Split.o )
[15 of 33] Compiling Utility.SafeCommand ( Utility/SafeCommand.hs, /tmp/nix-build-git-annex-6.20181011.drv-0/Utility/SafeCommand.o )
[16 of 33] Compiling Utility.FileSystemEncoding ( Utility/FileSystemEncoding.hs, /tmp/nix-build-git-annex-6.20181011.drv-0/Utility/FileSystemEncoding.o )
[17 of 33] Compiling Utility.SystemDirectory ( Utility/SystemDirectory.hs, /tmp/nix-build-git-annex-6.20181011.drv-0/Utility/SystemDirectory.o )
[18 of 33] Compiling Utility.Tmp      ( Utility/Tmp.hs, /tmp/nix-build-git-annex-6.20181011.drv-0/Utility/Tmp.o )
[19 of 33] Compiling Utility.Directory ( Utility/Directory.hs, /tmp/nix-build-git-annex-6.20181011.drv-0/Utility/Directory.o )
[20 of 33] Compiling Utility.UserInfo ( Utility/UserInfo.hs, /tmp/nix-build-git-annex-6.20181011.drv-0/Utility/UserInfo.o )
[21 of 33] Compiling Utility.Path     ( Utility/Path.hs, /tmp/nix-build-git-annex-6.20181011.drv-0/Utility/Path.o )
[22 of 33] Compiling Common           ( Common.hs, /tmp/nix-build-git-annex-6.20181011.drv-0/Common.o )
[23 of 33] Compiling Utility.DottedVersion ( Utility/DottedVersion.hs, /tmp/nix-build-git-annex-6.20181011.drv-0/Utility/DottedVersion.o )
[24 of 33] Compiling Git.Version      ( Git/Version.hs, /tmp/nix-build-git-annex-6.20181011.drv-0/Git/Version.o )
[25 of 33] Compiling Build.TestConfig ( Build/TestConfig.hs, /tmp/nix-build-git-annex-6.20181011.drv-0/Build/TestConfig.o )
[26 of 33] Compiling Build.Configure  ( Build/Configure.hs, /tmp/nix-build-git-annex-6.20181011.drv-0/Build/Configure.o )
[27 of 33] Compiling Utility.OSX      ( Utility/OSX.hs, /tmp/nix-build-git-annex-6.20181011.drv-0/Utility/OSX.o )
[28 of 33] Compiling Utility.FreeDesktop ( Utility/FreeDesktop.hs, /tmp/nix-build-git-annex-6.20181011.drv-0/Utility/FreeDesktop.o )
[29 of 33] Compiling Config.Files     ( Config/Files.hs, /tmp/nix-build-git-annex-6.20181011.drv-0/Config/Files.o )
[30 of 33] Compiling Assistant.Install.Menu ( Assistant/Install/Menu.hs, /tmp/nix-build-git-annex-6.20181011.drv-0/Assistant/Install/Menu.o )
[31 of 33] Compiling Assistant.Install.AutoStart ( Assistant/Install/AutoStart.hs, /tmp/nix-build-git-annex-6.20181011.drv-0/Assistant/Install/AutoStart.o )
[32 of 33] Compiling Build.DesktopFile ( Build/DesktopFile.hs, /tmp/nix-build-git-annex-6.20181011.drv-0/Build/DesktopFile.o )
[33 of 33] Compiling Main             ( Setup.hs, /tmp/nix-build-git-annex-6.20181011.drv-0/Main.o )
Linking Setup ...
configuring
patching script interpreter paths in .
./ghci: interpreter directive changed from "/bin/sh" to "/nix/store/lw7xaqhakk0i1c631m3cvac3x4lc5gr5-bash-4.4-p12/bin/sh"
./Build/mdwn2man: interpreter directive changed from "/usr/bin/env perl" to "/nix/store/l6qc2aa8vf6sxpmi7cw28nrihhmmmvp5-perl-5.24.3/bin/perl"
./Build/collect-ghc-options.sh: interpreter directive changed from "/bin/sh" to "/nix/store/lw7xaqhakk0i1c631m3cvac3x4lc5gr5-bash-4.4-p12/bin/sh"
./debian/rules: interpreter directive changed from "/usr/bin/make -f" to "/nix/store/cxgvqnp9cf8l1s58nplfzbwgwxnvkarc-gnumake-4.2.1/bin/make -f"
./debian/create-standalone-changelog: interpreter directive changed from "/bin/bash" to "/nix/store/lw7xaqhakk0i1c631m3cvac3x4lc5gr5-bash-4.4-p12/bin/bash"
./doc/tips/automatically_adding_metadata/pre-commit-annex: interpreter directive changed from "/bin/sh" to "/nix/store/lw7xaqhakk0i1c631m3cvac3x4lc5gr5-bash-4.4-p12/bin/sh"
./doc/special_remotes/external/example.sh: interpreter directive changed from "/bin/sh" to "/nix/store/lw7xaqhakk0i1c631m3cvac3x4lc5gr5-bash-4.4-p12/bin/sh"
./doc/special_remotes/external/git-annex-remote-ipfs: interpreter directive changed from "/bin/sh" to "/nix/store/lw7xaqhakk0i1c631m3cvac3x4lc5gr5-bash-4.4-p12/bin/sh"
./doc/special_remotes/external/git-annex-remote-torrent: interpreter directive changed from "/bin/sh" to "/nix/store/lw7xaqhakk0i1c631m3cvac3x4lc5gr5-bash-4.4-p12/bin/sh"
./doc/install/Android/git-annex-install: interpreter directive changed from "/bin/sh" to "/nix/store/lw7xaqhakk0i1c631m3cvac3x4lc5gr5-bash-4.4-p12/bin/sh"
./standalone/osx/git-annex.app/Contents/MacOS/git: interpreter directive changed from "/bin/sh" to "/nix/store/lw7xaqhakk0i1c631m3cvac3x4lc5gr5-bash-4.4-p12/bin/sh"
./standalone/osx/git-annex.app/Contents/MacOS/git-upload-pack: interpreter directive changed from "/bin/sh" to "/nix/store/lw7xaqhakk0i1c631m3cvac3x4lc5gr5-bash-4.4-p12/bin/sh"
./standalone/osx/git-annex.app/Contents/MacOS/git-shell: interpreter directive changed from "/bin/sh" to "/nix/store/lw7xaqhakk0i1c631m3cvac3x4lc5gr5-bash-4.4-p12/bin/sh"
./standalone/osx/git-annex.app/Contents/MacOS/git-receive-pack: interpreter directive changed from "/bin/sh" to "/nix/store/lw7xaqhakk0i1c631m3cvac3x4lc5gr5-bash-4.4-p12/bin/sh"
./standalone/osx/git-annex.app/Contents/MacOS/git-annex-webapp: interpreter directive changed from "/bin/sh" to "/nix/store/lw7xaqhakk0i1c631m3cvac3x4lc5gr5-bash-4.4-p12/bin/sh"
./standalone/osx/git-annex.app/Contents/MacOS/runshell: interpreter directive changed from "/bin/sh" to "/nix/store/lw7xaqhakk0i1c631m3cvac3x4lc5gr5-bash-4.4-p12/bin/sh"
./standalone/osx/git-annex.app/Contents/MacOS/git-annex: interpreter directive changed from "/bin/sh" to "/nix/store/lw7xaqhakk0i1c631m3cvac3x4lc5gr5-bash-4.4-p12/bin/sh"
./standalone/osx/git-annex.app/Contents/MacOS/git-annex-shell: interpreter directive changed from "/bin/sh" to "/nix/store/lw7xaqhakk0i1c631m3cvac3x4lc5gr5-bash-4.4-p12/bin/sh"
./standalone/linux/skel/git: interpreter directive changed from "/bin/sh" to "/nix/store/lw7xaqhakk0i1c631m3cvac3x4lc5gr5-bash-4.4-p12/bin/sh"
./standalone/linux/skel/git-upload-pack: interpreter directive changed from "/bin/sh" to "/nix/store/lw7xaqhakk0i1c631m3cvac3x4lc5gr5-bash-4.4-p12/bin/sh"
./standalone/linux/skel/git-shell: interpreter directive changed from "/bin/sh" to "/nix/store/lw7xaqhakk0i1c631m3cvac3x4lc5gr5-bash-4.4-p12/bin/sh"
./standalone/linux/skel/git-receive-pack: interpreter directive changed from "/bin/sh" to "/nix/store/lw7xaqhakk0i1c631m3cvac3x4lc5gr5-bash-4.4-p12/bin/sh"
./standalone/linux/skel/git-annex-webapp: interpreter directive changed from "/bin/sh" to "/nix/store/lw7xaqhakk0i1c631m3cvac3x4lc5gr5-bash-4.4-p12/bin/sh"
./standalone/linux/skel/runshell: interpreter directive changed from "/bin/sh" to "/nix/store/lw7xaqhakk0i1c631m3cvac3x4lc5gr5-bash-4.4-p12/bin/sh"
./standalone/linux/skel/git-annex: interpreter directive changed from "/bin/sh" to "/nix/store/lw7xaqhakk0i1c631m3cvac3x4lc5gr5-bash-4.4-p12/bin/sh"
./standalone/linux/skel/git-annex-shell: interpreter directive changed from "/bin/sh" to "/nix/store/lw7xaqhakk0i1c631m3cvac3x4lc5gr5-bash-4.4-p12/bin/sh"
./standalone/windows/build-simple.sh: interpreter directive changed from "/bin/sh" to "/nix/store/lw7xaqhakk0i1c631m3cvac3x4lc5gr5-bash-4.4-p12/bin/sh"
./standalone/windows/build.sh: interpreter directive changed from "/bin/sh" to "/nix/store/lw7xaqhakk0i1c631m3cvac3x4lc5gr5-bash-4.4-p12/bin/sh"
configureFlags: --verbose --prefix=/nix/store/p5jgab3hr5n4irndr1q9kxfn5xg4dm4r-git-annex-6.20181011 --libdir=$prefix/lib/$compiler --libsubdir=$pkgid --docdir=/nix/store/k90da4i17w2vvyca3aqciiyac8kzmhy9-git-annex-6.20181011-doc/share/doc --with-gcc=gcc --package-db=/tmp/nix-build-git-annex-6.20181011.drv-0/package.conf.d --ghc-option=-j1 --disable-split-objs --disable-library-profiling --disable-profiling --enable-shared --disable-coverage --enable-library-vanilla --disable-executable-dynamic --enable-tests --ghc-option=-split-sections -fassistant -fcryptonite -fdbus -fdesktopnotify -fdns -ffeed -finotify -fpairing -fproduction -fquvi -fs3 -ftahoe -ftdfa -ftestsuite -ftorrentparser -fwebapp -fwebapp-secure -fwebdav -fxmpp --extra-lib-dirs=/nix/store/54cwjh1lsmjpk2cbs43gw89w4zhk3ybb-ncurses-6.0-20171125/lib --extra-lib-dirs=/nix/store/wc2ll61lypsv9yig6mvy73c0lw1dp15a-gmp-6.1.2/lib --extra-lib-dirs=/nix/store/54cwjh1lsmjpk2cbs43gw89w4zhk3ybb-ncurses-6.0-20171125/lib --extra-lib-dirs=/nix/store/nn7nn091r8xbqj1dj03xg2js15a1pkgi-bup-0.29.1/lib --extra-lib-dirs=/nix/store/g8kvip8c7hkz8hj4fp316pjb20mw0i3y-gnupg-2.2.8/lib --extra-lib-dirs=/nix/store/l6qc2aa8vf6sxpmi7cw28nrihhmmmvp5-perl-5.24.3/lib
  checking UPGRADE_LOCATION... not available
  checking git... no
  checking git version...git: createProcess: runInteractiveProcess: exec: does not exist (No such file or directory)
builder for '/nix/store/q1r40skrfc5dj3wwj4048y4z3ijigl0y-git-annex-6.20181011.drv' failed with exit code 1
error: build of '/nix/store/q1r40skrfc5dj3wwj4048y4z3ijigl0y-git-annex-6.20181011.drv' failed
```

**Comment by peti** [comment] 2018-10-31 11:20
It's not possible to say anything about this issue unless you share more information about your setup, i.e. which version if `cabal2nix` are you using, how to you use it to generate a Nix expression, and what does this Nix expression look like? What version (channel) of Nix do you use?

Chances are that the issue is not caused by `cabal2nix` itself (since it clearly *does* include `git` as a build-time dependency) but rather by the way you are using the generated expression.

**Comment by seanparsons** [comment] 2018-11-03 11:40
I've managed to create a minimal repro which is: 

- Clone latest git- annex source.
- With cabal2nix 2.9.2 on NixOS 18.03 run `cabal2nix . > git-annex.nix`.
- Create the following `default.nix` file:
```
{ nixpkgs ? import <nixpkgs> {}, compiler ? "ghc822" }:
nixpkgs.pkgs.haskell.packages.${compiler}.callPackage ./git-annex.nix { }
```
- Run `nix-build .`.

**Comment by peti** [comment] 2018-11-03 11:46
Calling the `git-annex.nix` expression without any explicit arguments means that all missing names will be resolved in the Haskell package set. Therefore, `git` will be resolved to the package http://hackage.haskell.org/package/git, which is not what you want. To avoid this issue, make sure that system packages are mentioned explicitly as such:

    { nixpkgs ? import <nixpkgs> {}, compiler ? "ghc822" }:
    nixpkgs.pkgs.haskell.packages.${compiler}.callPackage ./git-annex.nix {
      inherit (pkgs) bup curl git gnupg lsof openssh perl rsync wget which;
    }

**Closed by peti** 2018-11-03 11:46 UTC

**Comment by seanparsons** [comment] 2018-11-03 12:04
@peti That suddenly makes a whole lot more sense, thanks for that.

Does that mean there's the possibility of collisions by name though?

**Comment by peti** [comment] 2018-11-03 14:56
Yes, it's possible that both a system library and a Haskell dependency are called `abc` and therefore their generated binding names collide. It hasn't happened very much in practice, though.
