### ISSUE TITLE
Doesn't work in directories starting with a '.' (e.g. '.xmonad')

### ISSUE THREAD

**Issue by samdoshi** [NixOS/cabal2nix#415] opened 2019-05-03 19:33 UTC
I believe there is a general issue when working with `cabal2nix` (and `callCaba2nix`), whereby any local packages that are in directories that start with a dot (e.g. `.xmonad`) fail to build with the error message:

```
illegal name: '.xmonad'
```

---

Here is a minimal example:

`.test/test.cabal`:

```
name:                test
version:             0.1.0.0
build-type:          Simple
cabal-version:       >=1.10

executable test
  hs-source-dirs:      .
  main-is:             Main.hs
  default-language:    Haskell2010
  build-depends:       base >= 4.9 && < 5
```

`.test/Main.hs`:

```
main = putStrLn "Hello, world!"
```

`.test/default.nix`:

```
{ pkgs ? import <nixpkgs> {} }:

{
  test = pkgs.haskellPackages.callCabal2nix "test" ./. {};
}
```

And then building it with this:

```nix build --show-trace -f .```

```
error: while evaluating 'callCabal2nix' at /nix/store/3r86krbw1sb6bnmrhr93n6nd12ygwvap-nixos-19.03.172392.6d7ed964296/nixos/pkgs/development/haskell-modules/make-package-set.nix:206:32, called from /home/sam/Scratch/broken-cabal2nix/.test/default.nix:4:10:
while evaluating 'callCabal2nixWithOptions' at /nix/store/3r86krbw1sb6bnmrhr93n6nd12ygwvap-nixos-19.03.172392.6d7ed964296/nixos/pkgs/development/haskell-modules/make-package-set.nix:191:66, called from /nix/store/3r86krbw1sb6bnmrhr93n6nd12ygwvap-nixos-19.03.172392.6d7ed964296/nixos/pkgs/development/haskell-modules/make-package-set.nix:206:38:
while evaluating 'overrideCabal' at /nix/store/3r86krbw1sb6bnmrhr93n6nd12ygwvap-nixos-19.03.172392.6d7ed964296/nixos/pkgs/development/haskell-modules/lib.nix:37:24, called from /nix/store/3r86krbw1sb6bnmrhr93n6nd12ygwvap-nixos-19.03.172392.6d7ed964296/nixos/pkgs/development/haskell-modules/make-package-set.nix:202:10:
while evaluating 'callPackageKeepDeriver' at /nix/store/3r86krbw1sb6bnmrhr93n6nd12ygwvap-nixos-19.03.172392.6d7ed964296/nixos/pkgs/development/haskell-modules/make-package-set.nix:156:33, called from /nix/store/3r86krbw1sb6bnmrhr93n6nd12ygwvap-nixos-19.03.172392.6d7ed964296/nixos/pkgs/development/haskell-modules/make-package-set.nix:202:25:
while evaluating 'overrideCabal' at /nix/store/3r86krbw1sb6bnmrhr93n6nd12ygwvap-nixos-19.03.172392.6d7ed964296/nixos/pkgs/development/haskell-modules/lib.nix:37:24, called from /nix/store/3r86krbw1sb6bnmrhr93n6nd12ygwvap-nixos-19.03.172392.6d7ed964296/nixos/pkgs/development/haskell-modules/make-package-set.nix:157:5:
while evaluating 'callPackage' at /nix/store/3r86krbw1sb6bnmrhr93n6nd12ygwvap-nixos-19.03.172392.6d7ed964296/nixos/pkgs/development/haskell-modules/make-package-set.nix:114:22, called from /nix/store/3r86krbw1sb6bnmrhr93n6nd12ygwvap-nixos-19.03.172392.6d7ed964296/nixos/pkgs/development/haskell-modules/make-package-set.nix:157:20:
while evaluating 'callPackageWithScope' at /nix/store/3r86krbw1sb6bnmrhr93n6nd12ygwvap-nixos-19.03.172392.6d7ed964296/nixos/pkgs/development/haskell-modules/make-package-set.nix:74:37, called from /nix/store/3r86krbw1sb6bnmrhr93n6nd12ygwvap-nixos-19.03.172392.6d7ed964296/nixos/pkgs/development/haskell-modules/make-package-set.nix:114:28:
while evaluating 'makeOverridable' at /nix/store/3r86krbw1sb6bnmrhr93n6nd12ygwvap-nixos-19.03.172392.6d7ed964296/nixos/lib/customisation.nix:67:24, called from /nix/store/3r86krbw1sb6bnmrhr93n6nd12ygwvap-nixos-19.03.172392.6d7ed964296/nixos/pkgs/development/haskell-modules/make-package-set.nix:97:8:
while evaluating 'drvScope' at /nix/store/3r86krbw1sb6bnmrhr93n6nd12ygwvap-nixos-19.03.172392.6d7ed964296/nixos/pkgs/development/haskell-modules/make-package-set.nix:87:18, called from /nix/store/3r86krbw1sb6bnmrhr93n6nd12ygwvap-nixos-19.03.172392.6d7ed964296/nixos/lib/customisation.nix:69:12:
while evaluating the attribute 'installPhase' of the derivation 'cabal2nix-test' at /nix/store/3r86krbw1sb6bnmrhr93n6nd12ygwvap-nixos-19.03.172392.6d7ed964296/nixos/pkgs/development/haskell-modules/make-package-set.nix:125:7:
illegal name: '.test'
````

**Renaming the directory `.test.` to `test`, fixes all of it.** (I've also tested it using the output from `cabal2nix` and with `nixpkgs` unstable.)

I'm a long way from really being able to decipher that backtrace, but I think the issue is that it's trying to package up the source code for the build and giving it a package name based on it's directory.

**Comment by peti** [comment] 2019-05-07 12:39
You might want to report this issue in the https://github.com/NixOS/nixpkgs repository. `cabal2nix` itself doesn't care about directory names and I think it's unlikely that this issue can be fixed by this utility. Rather, the issue is probably in the Nix code that calls this utility.

**Closed by peti** 2019-05-07 12:39 UTC
