### ISSUE TITLE
Can't build cabal2nix-20180903

### ISSUE THREAD

**Issue by drvink** [NixOS/cabal2nix#203] opened 2015-09-07 11:01 UTC
```
setupCompileFlags: -package-db=/tmp/nix-build-language-nix-20180903.drv-0/package.conf.d -j1 -threaded
[1 of 1] Compiling Main             ( Setup.lhs, /tmp/nix-build-language-nix-20180903.drv-0/Main.o )
Linking Setup ...
configuring
configureFlags: --verbose --prefix=/nix/store/xi3vpn4sps5s32ngqha85r0ap3jgjbhq-language-nix-20180903 --libdir=$prefix/lib/$compiler --libsubdir=$pkgid --with-gcc=gcc --package-db=/tmp/nix-build-language-nix-20180903.drv-0/package.conf.d --ghc-option=-optl=-Wl,-rpath=/nix/store/xi3vpn4sps5s32ngqha85r0ap3jgjbhq-language-nix-20180903/lib/ghc-7.10.2/language-nix-20180903 --enable-split-objs --enable-library-profiling --disable-executable-profiling --enable-shared --enable-library-vanilla --enable-executable-dynamic --disable-tests
Configuring language-nix-20180903...
Setup: At least the following dependencies are missing:
QuickCheck -any, doctest -any
builder for ‘/nix/store/217zjxqjir2n2y0vy2pfz08yvvhp1i54-language-nix-20180903.drv’ failed with exit code 1
cannot build derivation ‘/nix/store/maa763ra9br7i1pxcczv56r3sy6hg0x5-cabal2nix-20180903.drv’: 1 dependencies couldn't be built
error: build of ‘/nix/store/maa763ra9br7i1pxcczv56r3sy6hg0x5-cabal2nix-20180903.drv’ failed
```

```
vm[1158]:~% ghc-pkg list QuickCheck
/nix/store/17zlbd71g5slpc4gkcacnq64yncsdvh4-ghc-7.10.2/lib/ghc-7.10.2/package.conf.d
   QuickCheck-2.8.1
vm[1159]:~% ghc-pkg list doctest
/nix/store/17zlbd71g5slpc4gkcacnq64yncsdvh4-ghc-7.10.2/lib/ghc-7.10.2/package.conf.d
   doctest-0.10.1
```

Help?

**Comment by peti** [comment] 2015-09-07 11:48
What version of Nixpkgs are you using? There were build errors of `cabal2nix` in the past, but IMHO they've all been fixed in `master` (a.k.a. `nixos-unstable`) and `release-15.09`.  Also, could you please past the exact command you're using to run that build? What platform do you use?

**Comment by drvink** [comment] 2015-09-07 12:49
I'm using nixos-unstable. The command I'm using is `nix-env -f ~/nix -i`, but that doesn't help without the `default.nix`, which follows:

```nix
{ pkgs ? (import <nixpkgs> {})
, system ? builtins.currentSystem }:

let
  self = with pkgs; {
    inherit
      #cabal2nix
      glibcLocales # work around https://github.com/NixOS/nix/issues/599
      ncurses
      nix-prefetch-scripts
      nix-repl
      openssl;

    mdl-haskell-env =
      with pkgs.haskellPackages;
      let
        pkgs = [
          attoparsec doctest hashtables haskell-src-exts ListLike
          mono-traversable network optparse-applicative parsec prelude-extras
          process QuickCheck regex-base regex-compat-tdfa regex-posix regex-tdfa
          split text vector
        ];
        tools = [
          alex cabal-install cpphs ghc-mod ghci-ng happy haskell-docs hdevtools
          hscolour
        ]; in
      ghcWithPackages (hp: pkgs ++ tools);
  }; in
self
```

And my `~/.nixpkgs/config.nix`:

```nix
{ pkgs }:

{
  allowUnfree = true;

  haskellPackageOverrides = self: super: with pkgs.haskell.lib; {
    mkDerivation = args: super.mkDerivation (args // {
      doCheck = false;
      enableLibraryProfiling = true;
      hyperlinkSource = true;

      # XXX HACK the ghc-mod override in
      # pkgs/development/haskell-modules/configuration-common.nix
      # drags in a ton of extra packages by declaring emacs as an
      # executable tool dependency; we work around it by avoiding
      # compilation of the elisp files, but it would be preferable if
      # we could compile them iff emacs is present on the machine.  we
      # have to do the override here instead of in the ghc-mod block
      # because the problematic overrides are applied *after* the ones
      # in the ghc-mod block
      executableToolDepends =
        let xs = args.executableToolDepends or []; in
        if args.pname != "ghc-mod" then xs else
        builtins.filter (x: x != pkgs.emacs) xs;
      postInstall =
        let pi = args.postInstall or ""; in
        if args.pname != "ghc-mod" then pi else ''
          local lispdir=( "$out/share/"*"-${self.ghc.name}/${args.pname}-${args.version}/elisp" )
          # make -C $lispdir
          mkdir -p $out/share/emacs/site-lisp
          #ln -s "$lispdir/"*.el{,c} $out/share/emacs/site-lisp/
          ln -s "$lispdir/"*.el $out/share/emacs/site-lisp/
        '';
    });

    ghc-mod = overrideCabal super.ghc-mod (drv: {
      src = pkgs.fetchFromGitHub {
        owner = "kazu-yamamoto";
        repo = "ghc-mod";
        rev = "8fea4ac426331cc919a83a4c216c682e50454b41";
        sha256 = "140447cp1n1ansmii4vk5y8x0r32px3a11795c8via2qhgaxnfy1";
      };
    });

    ghci-ng = overrideCabal super.ghci-ng (drv: {
      src = pkgs.fetchFromGitHub {
        owner = "chrisdone";
        repo = "ghci-ng";
        rev = "738f66f3d1f1a3b7ba574fb9c83da793179a42c3";
        sha256 = "0flawgqdn01axkzac3zkzzqgbjm7z7b4y0xwcvr360x1fbnmmp52";
      };
      executableHaskellDepends =
        let deps = with super; [ containers syb time transformers ];
        in drv.executableHaskellDepends ++ deps;
      version = "0.0.0";
      homepage = "https://github.com/chrisdone/ghci-ng";
      description = "Next generation GHCi";
    });

    haskell-docs = overrideCabal super.haskell-docs (drv: {
      src = pkgs.fetchFromGitHub {
        owner = "chrisdone";
        repo = "haskell-docs";
        rev = "431e08e422c12f684712d4d8abd67ce0d73b9505";
        sha256 = "0s3zzn9p418n4a2kgrwc18mcmravwlag5c1djdi19lpj4k1qxk8j";
      };
      patches = [ ~/nix/patches/haskell-docs/0001-packagename-type-ambiguity.patch ];
    });
  };

  packageOverrides = super: let self = super.pkgs; in {
    nix-repl = pkgs.lib.overrideDerivation super.nix-repl (drv: {
      src = pkgs.fetchFromGitHub {
        owner = "edolstra";
        repo = "nix-repl";
        rev = "8a2f5f0607540ffe56b56d52db544373e1efb980";
        sha256 = "0cjablz01i0g9smnavhf86imwx1f9mnh5flax75i615ml71gsr88";
      };
    });
  };
}
```

**Comment by peti** [comment] 2015-09-07 13:06
Does the command `nix-env -f "<nixpkgs>" -iA cabal2nix` succeed when you comment out all those overrides you've configured in `~/.nixpkgs/config.nix`?

**Comment by drvink** [comment] 2015-09-07 13:12
Yes, it fetches the binary package and installs it.

**Comment by peti** [comment] 2015-09-07 13:20
Well, I suppose the problem is in your overrides then, no?

**Comment by drvink** [comment] 2015-09-07 13:29
Not really: the problem is in nixpkgs somewhere, because the only "global" overrides set here are `doCheck = false`, `enableLibraryProfiling = true`, and `hyperlinkSource = true`, which are morally equivalent to setting the following in `~/.cabal/config`:

```
tests: False
library-profiling: True
haddock
  hyperlink-source: True
```

(I note that `tests: False` is a Cabal default.)

**Comment by drvink** [comment] 2015-09-07 13:45
https://github.com/NixOS/cabal2nix/blob/master/language-nix/language-nix.cabal

```
library
  hs-source-dirs:
      src
  ghc-options: -Wall
  build-depends:
      base < 5
    , deepseq
    , doctest
    , lens
    , pretty >= 1.1.2
    , QuickCheck
    , regex-posix
  exposed-modules:
      Language.Nix
      Language.Nix.Binding
      Language.Nix.Identifier
      Language.Nix.Path
  default-language: Haskell2010
```

Why does the *library itself* depend on QuickCheck and doctest when only the tests require them? Meanwhile, in `nixpkgs/pkgs/development/tools/haskell/cabal2nix/language-nix.nix`:

```nix
  libraryHaskellDepends = [
    base deepseq lens pretty regex-posix
  ];
```

**Closed** 2015-09-07 14:04 UTC
Labels: bug

**Comment by drvink** [comment] 2015-09-07 17:00
@peti:

I appreciate the fact that you've "fixed" the issue, despite quietly not acknowledging that the problem was, in fact, yours, and having first taken the opportunity to smugly insult me by telling me that my configuration was to blame even though you hadn't bothered to investigate first.

So, now it will install. Good job. Unfortunately, your sloppy fix still misses the point, which is that _**your dependencies are specified incorrectly**_, so you're dragging in a ton of extra dependencies that are only needed for running tests, even when the user says _**they don't care about running tests**_.

Here is how you could fix it, if you actually care:

* For `distribution-nixpkgs.nix`:
  * Remove `doctest` and `hspec` from `libraryHaskellDepends`
  * Remove the same packages from the `library` spec in the `.cabal` file
* For `language-nix.nix`:
  * Same as above

Result:

```
vm[1341]:~% find /nix/store \( -iname '*hunit*' -o -iname '*doctest*' \) -print
/nix/store/zrny7m8nmn9q9klrr32alyfkkf113wc8-python-2.7.10/lib/python2.7/doctest.pyo
/nix/store/zrny7m8nmn9q9klrr32alyfkkf113wc8-python-2.7.10/lib/python2.7/doctest.py
/nix/store/zrny7m8nmn9q9klrr32alyfkkf113wc8-python-2.7.10/lib/python2.7/doctest.pyc
vm[1342]:~% cabal2nix --version
cabal2nix 20180903
```

See? No unnecessary dependencies,.

Sometimes, I don't know why I try to be helpful. I have a bunch of roaches running around my God damn house even though I don't keep any garbage inside and I clean and vacuum daily, I've been out of work for months after losing my dream job because I had a nervous breakdown from being terminally afraid of making mistakes, and I can't get so much as an "oh, sorry for your trouble" when I report a problem with someone's stuff. You know what _**I**_ did when someone reported a problem with my software? [I spent about a day on and off over the course of a month or two hunting down their issue, being gracious the entire time, not *blaming* them for anything.](https://github.com/drvink/epanos/issues/1)

I'm really fucking tired of how people have a habit of reacting to problem reports. Can't we all just treat each other with respect instead of automatically assuming that the user is an idiot? We all have to deal with these godawful, dehumanizing, piece of shit machines together, nearly every day of our careers/lives. We're all in this together.

Cheers, and thanks for cabal2nix. Also, the year isn't 2018.

**Comment by peti** [comment] 2015-09-08 11:22
@drvink,

> I appreciate the fact that you've "fixed" the issue, despite quietly not acknowledging that the problem was, in fact, yours, and having first taken the opportunity to smugly insult me by telling me that my configuration was to blame even though you hadn't bothered to investigate first.

You are right. Because of time constraints, I can work on this project only in small bursts spread out all over the day, which is no ideal way to develop software, especially since I'm in the middle of an extensive re-factoring. I try to get things done under these conditions by adopting an intense focus: when I have half an hour to spare for `cabal2nix`, then I set myself some goal and work on that problem only without looking left or right. Considerations other than "add flag XYZ to the command-line parser" or "move function ZYX out of the X.Y.Z module" basically don't enter my mind.

So your bug report comes in while I'm working on a feature, and a report that says *cabal2nix doesn't compile* represents a serious problem IMHO that needs to be addressed quickly. It turns out, however, that the package *does* compile, only it won't compile with the overrides applied that you've configured. In that situation, I made a snap judgment and assumed that the reason for the build failure must be the overrides, at which point I decided to shift my attention back to the code I was working on instead of examining your overrides for the reason why they make the build fail. On some other occasion, I might have tried to understand what is happening exactly, but at that particular moment I felt that I had things to do that are more important to me.

Now, your overrides were perfectly fine and they simply uncovered an issue in the Nixpkgs build descriptions. When I realized that this was the case, I fixed the issue, but I didn't take the time to re-consider the interaction that had taken place between us. In hindsight, it would have been an act of basic decency to acknowledge that I had misjudged the situation and blamed your code for a bug that was, in fact, in my code. I am sorry that this has happened, and I am sorry for not even realizing I had been rude until way, way after the fact.

The consideration of how you might feel because of the way I responded to your bug report had simply not entered my mind, because I was too preoccupied with code to pay attention to the way I interact with another human being.


> Your fix still misses the point, which is that *your dependencies are specified incorrectly*, so you're dragging in a ton of extra dependencies that are only needed for running tests, even when the user says *they don't care about running tests*.

Until recently, the Emacs `haskell-mode` couldn't determine the environment in which it must run `ghci` so that all required libraries are visible in an interactive session. Instead of adopting to the proper context, it used the environment defined for the library target regardless of whether you were editing a library file or not. In particular, this mean that interactive Haskell sessions for files belonging to the test suite were broken. I worked around that issue by registering the test-suite-specific dependencies to the library as well, so that I could edit all my bloody source files and test them interactively without running into errors all over the place.

It turns out that recent versions of `haskell-mode` no longer have that problem, so I've updated the Cabal files accordingly. The next `cabal2nix` release to Nixpkgs won't have over-specified dependencies any more.


> Also, the year isn't 2018.

Yes, that is true. I've fixed the bogus version string in Nixpkgs and updated the tags in this repository too. Thank you for drawing my attention to this issue.
