### ISSUE TITLE
Breaks when depending on the assert package

### ISSUE THREAD

**Issue by ElvishJerricco** [NixOS/cabal2nix#254] opened 2016-12-17 06:09 UTC
There's a package called [assert](https://hackage.haskell.org/package/assert) that breaks the output of `cabal2nix` if you depend on it. `assert` is a keyword in Nix, so you can't use it naked like `cabal2nix` does in the generated derivation.

This isn't *really* an issue, since the package is pretty much completely irrelevant and literally nothing depends on it. I'm mostly just curious what the solution to this should be, because I'm running into the same problem in my attempt to make something like `cabal2nix` for PureScript's new package sets. The PureScript `assert` package is actually used fairly often.

**Comment by peti** [comment] 2016-12-18 12:31
This is a duplicate of https://github.com/NixOS/cabal2nix/issues/164. We have no (good) solution for this issue yet. I suppose we'll need to mange invalid identifiers like this one.

**Closed by peti** 2016-12-18 12:31 UTC
