### ISSUE TITLE
cabal2nix does not generate nix file for the specified version

### ISSUE THREAD

**Issue by themattchan** [NixOS/cabal2nix#299] opened 2017-08-29 23:04 UTC
```
$ cabal2nix cabal://hashable-1.2.4.0 >! nix/hashable.nix

$ cat nix/hashable.nix
{ mkDerivation, base, bytestring, criterion, deepseq, ghc-prim
, HUnit, integer-gmp, QuickCheck, random, siphash, stdenv
, test-framework, test-framework-hunit, test-framework-quickcheck2
, text, unix
}:
mkDerivation {
  pname = "hashable";
  version = "1.2.6.1";
  sha256 = "0ymv2mcrrgbdc2w39rib171fwnhg7fgp0sy4h8amrh1vw64qgjll";
  revision = "2";
  editedCabalFile = "0w4756sa04nk2bw3vnysb0y9d09zzg3c77aydkjfxz1hnl1dvnjn";
  isLibrary = true;
  isExecutable = true;
  libraryHaskellDepends = [
    base bytestring deepseq ghc-prim integer-gmp text
  ];
  testHaskellDepends = [
    base bytestring ghc-prim HUnit QuickCheck random test-framework
    test-framework-hunit test-framework-quickcheck2 text unix
  ];
  benchmarkHaskellDepends = [
    base bytestring criterion ghc-prim integer-gmp siphash text
  ];
  homepage = "http://github.com/tibbe/hashable";
  description = "A class for types that can be converted to a hash value";
  license = stdenv.lib.licenses.bsd3;
}

$ cabal2nix --version
cabal2nix 2.4
```

(`1.2.6.1` is the latest version on hackage)

**Comment by peti** [comment] 2017-09-01 12:25
Duplicate of https://github.com/NixOS/cabal2nix/issues/293.

**Closed by peti** 2017-09-01 12:25 UTC
