### ISSUE TITLE
URL using bad/illegal format or missing URL (3)

### ISSUE THREAD

**Issue by Rizary** [NixOS/cabal2nix#419] opened 2019-05-22 22:32 UTC
I have file called `compressed.nix` that contains the following code:
```
{ system ? builtins.currentSystem
}:

let 
  reflex-platform   = import (import ./nixdeps/reflex-platform) {inherit system;};
  
  haskellLib        = pkgs.haskell.lib;
  inherit (reflex-platform) nixpkgs;
  inherit (nixpkgs) lib;

  pkgs = nixpkgs;

  monoReflexFun = (reflex-platform.project ({ pkgs, ... }: {
    packages = {
      frontend = ./landing-static;
    };

    shells = {
      ghcjs = ["frontend"];
    };

    overrides = self: super:
      let fast = p: haskellLib.dontHaddock (haskellLib.dontCheck p);
      in rec { frontend = fast super.frontend; };
  })).ghcjs.frontend;

  landingPage = monoReflexFun;

in {
  minified-landing  = landingPage;
}
```

the reflex-platform's deps is a simple `fetchFromGitHub` function that call specefic github rev. When I try to build using `nix-build compressed.nix` i got the following error:
```
building '/nix/store/znv8df9nmwaaypd2syaspa9g8kbih33l-cabal2nix-frontend.drv'...
installing
unpacking...
tar: This does not look like a tar archive
tar: Exiting with failure status due to previous errors
error: program 'tar' failed with exit code 2
error: unable to download '/nix/store/yr8xxzx8pqr87q7vjm2jia5c58wx1hi7-landing-static': URL using bad/illegal format or missing URL (3)
** need a revision for VCS when the hash is given. skipping.
** need a revision for VCS when the hash is given. skipping.
** need a revision for VCS when the hash is given. skipping.
** need a revision for VCS when the hash is given. skipping.
cabal2nix: user error (Failed to fetch source. Does this source exist? Source {sourceUrl = "/nix/store/yr8xxzx8pqr87q7vjm2jia5c58wx1hi7-landing-static", sourceRevision = "", sourceHash = Guess "", sourceCabalDir = ""})
builder for '/nix/store/znv8df9nmwaaypd2syaspa9g8kbih33l-cabal2nix-frontend.drv' failed with exit code 1
error: build of '/nix/store/znv8df9nmwaaypd2syaspa9g8kbih33l-cabal2nix-frontend.drv' failed
(use '--show-trace' to show detailed location information)
```

I am using nix on ubuntu and when I try to built in my nixos vm, i got the same error, but with additional line of error which is ` error: creating directory '/nix/var': Permission denied`

**Comment by endgame** [comment] 2019-05-22 23:57
This bug has a lot of details that are specific to your setup. Can you construct a minimal breaking example that someone who is not you can try and run?

**Comment by Rizary** [comment] 2019-05-23 01:05
@endgame hi.. I use nix on WSL version 2.2.2

this is minimal repo: `https://github.com/Rizary/Reflex-website` that I want to build.

I just follow this `https://github.com/ElvishJerricco/reflex-project-skeleton` but instead of using submodule, I use `fetchFromGitHub` function in my `nixdeps/reflex-platform/default.nix`. 

Comparing to the reflex-project-skeleton, which builds successfully ( I make submodule and nixdeps have the same `rev`), my repo got the above error.

**Comment by endgame** [comment] 2019-05-23 12:01
I've done a lot of digging, and I think you have made the following errors:

* The `packages` sent in the argument to `reflex-platform` should name the cabal package: see here for docs on the `project` function: https://github.com/reflex-frp/reflex-platform/blob/develop/project/default.nix#L56

* The `landing.cabal` file says `cabal-version: 2.4`, which cabal2nix cannot parse. Change that to `cabal-version: 2.2`

After doing both of those things `nix build -f . ghcjs.landing` completed successfully on my machine. I recommend closing this issue as it's not a bug.

**Closed** 2019-05-23 13:55 UTC
